baseURL = "https://app.claritus.io/"
languageCode = "en-us"
title = "Claritus - A simple way to control your wealth"

theme = "clearvalue"
assetDir = 'themes/clearvalue/assets'

[params]
    gtagConfig = 'UA-159218662-2'
    appUrl = "https://app.claritus.io/"
