baseURL = "https://claritus.io/"
languageCode = "en-us"
title = "Claritus - The Simple Way to Keep Track of Your Wealth"

theme = "clearvalue"
assetDir = 'themes/clearvalue/assets'

[params]
    description = "Finally, a 360° view of your assets that lets you track, understand, and be in complete control of your wealth - all in one place!"
    gtagConfig = 'UA-159218662-2'
    appUrl = "https://app.claritus.io"

[permalinks]
  posts = "blog/:title"
