baseURL = "https://claritus.io/"
languageCode = "en-us"
title = "Claritus - The Simple Way to Keep Track of Your Wealth"

theme = "clearvalue"
assetDir = 'themes/clearvalue/assets'

[params]
    gtagConfig = 'UA-159218662-2'
    appUrl = "https://app.claritus.io"
