baseURL = "https://clearvalue.netlify.com/"
languageCode = "en-us"
title = "Clear Value - A simple way to control your wealth"

theme = "clearvalue"
assetDir = 'themes/clearvalue/assets'
[params]
    gtagConfig = 'UA-159218662-2'
