[build]
publish = "public"
command = "npm install && hugo --gc --minify"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        
#[[headers]]
#    for = "/images/*"
#    [headers.values]
#        Cache-Control = "public, s-max-age=604800"
[[headers]]
    for = "/scss/*.css"
    [headers.values]
        Cache-Control = "public, s-max-age=604800"
[[headers]]
    for = "/js/*.js"
    [headers.values]
        Cache-Control = "public, s-max-age=604800"

[context.production.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.79.0"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.79.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


[[redirects]]
from = "https://clearvalue.io"
to = "https://claritus.io"
status = 301
force = true

[[redirects]]
from = "https://claritus.io/faq/"
to = "https://claritus.io/how-it-work/"
status = 301
force = true

[[redirects]]
from = "https://claritus.io/core-values/"
to = "https://claritus.io/about-us/"
status = 301
force = true

[[redirects]]
from = "https://claritus.io/our-story/"
to = "https://claritus.io/about-us/#our-story"
status = 301
force = true

[[redirects]]
from = "https://claritus.io/how-it-work/"
to = "https://claritus.io/how-it-works/"
status = 301
force = true

[[redirects]]
from = "https://clearvalue.io/*"
to = "https://claritus.io/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.clearvalue.io"
to = "https://claritus.io"
status = 301
force = true

[[redirects]]
from = "https://www.clearvalue.io/*"
to = "https://claritus.io/:splat"
status = 301
force = true